name = "LuminaCC"
author = "The LuminaCC team"
version = "1.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "56005b9af52a5a63d2226bb76d870cee9603aadfecf756825040dcb36278f963"

[versions]
fabric = "0.16.3"
minecraft = "1.20.1"
