name = "LuminaCC"
author = "The LuminaCC team"
version = "1.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6cc10fa5ac5fa951e1574ebbec6063b72f906bac0a0550b8f4e9776532c12050"

[versions]
fabric = "0.16.3"
minecraft = "1.20.1"
