name = "LuminaCC"
author = "The LuminaCC team"
version = "1.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "33981fe8afefd0c6f49ad5b4b63e7d727b3b99cb83f0134dd57f1d40d72d7e8f"

[versions]
fabric = "0.16.3"
minecraft = "1.20.1"
