name = "LuminaCC"
author = "The LuminaCC team"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "33b716f5e7cb9785e01abdadd8b65889360ad6dc81722f2029fa4574f4f5b57b"

[versions]
fabric = "0.16.0"
minecraft = "1.20.1"
