name = "LuminaCC"
author = "The LuminaCC team"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "87e44668fc56ec11992aa519f7c1d51708470f8fd77a4eefc39be402acc6f9ca"

[versions]
fabric = "0.16.0"
minecraft = "1.20.1"
