name = "LuminaCC"
author = "The LuminaCC team"
version = "1.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b64136bb08b8c77fe29920ad9c8a65bf65285de08f3c18318f284c3e6b7ff059"

[versions]
fabric = "0.16.0"
minecraft = "1.20.1"
