name = "Lumina CC"
author = "autumntx"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7b5b88d9414ca456877abd06916f4bc9838323d3de37b887a58b69d923249f78"

[versions]
fabric = "0.16.0"
minecraft = "1.20.1"
